=== artcom/asl/xml/testdata/y60.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="Point3">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	
	<xs:simpleType name="Vector3">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	
	<xs:simpleType name="Vector4">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	
	<xs:simpleType name="Int2">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
		
	<xs:simpleType name="Matrix44">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	
	<xs:element name="scene">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="shapes" />
				<xs:element ref="materials"  />
				<xs:element ref="world" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="shapes">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="shape" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="materials">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="material" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="shape">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="positions"  />
				<xs:element ref="colors"  />
				<xs:element ref="normals"  />
				<xs:element ref="uvsets" />
				<xs:element ref="primitives" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" />
			<xs:attribute name="name" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="positions">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="position" type="Point3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="colors">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="color" type="Vector4" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="normals">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="normal" type="Vector3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="uvsets">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="uvset" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="uvset">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="uvcoord" type="Int2" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="primitives">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="triangle" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="triangle">
		<xs:complexType>
			<xs:sequence minOccurs="3" maxOccurs="3">
				<xs:element ref="vertex" />
			</xs:sequence>
			<xs:attribute name="materialref" type="xs:IDREF" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="vertex">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="parameter" />
			</xs:sequence>
			<xs:attribute name="position" type="xs:unsignedLong" />
			<xs:attribute name="normal" type="xs:unsignedLong" />
			<xs:attribute name="texcoords" type="VectorULong2" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="parameter">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" />
					<xs:attribute name="type" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="VectorULong2">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	
	<xs:element name="material">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="properties" />
				<xs:element ref="vertexparameters" />
				<xs:element ref="textures" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" />
			<xs:attribute name="type" type="xs:string" />
			<xs:attribute name="id" type="xs:ID" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="value" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="vertexparameters">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="value" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="textures">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="texture" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="value">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:string" />
					<xs:attribute name="type" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="texture">
		<xs:complexType>
			<xs:attribute name="src" type="xs:string" />
			<xs:attribute name="applymode" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
    <xs:element name="node" type="nodeType" abstract="true"/>
    
    <xs:complexType name="nodeType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="node" />
		</xs:sequence>
		<xs:attribute name="position" type="Point3" />
		<xs:attribute name="orientation" type="Point3" />
		<xs:attribute name="scale" type="Point3" />
    </xs:complexType>
    
	<xs:element name="world">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="node" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="body" substitutionGroup="node">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="nodeType">
					<xs:attribute name="shape" type="xs:IDREF" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="light" substitutionGroup="node">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="nodeType">
					<xs:attribute name="emitter" type="xs:IDREF" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="transform" substitutionGroup="node">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="nodeType">
					<xs:attribute name="type" type="xs:string" />
					<xs:attribute name="matrix" type="Matrix44" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== artcom/asl/xml/testdata/y60.xml
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="y60.xsd">
	<shapes>
		<shape name="W_rfel" id="s0">
			<positions>
				<position>[-100,-100,-100]</position>
				<position>[-100,100,-100]</position>
				<position>[100,-100,-100]</position>
				<position>[100,100,-100]</position>
				<position>[100,-100,100]</position>
				<position>[100,100,100]</position>
				<position>[-100,-100,100]</position>
				<position>[-100,100,100]</position>
			</positions>
			<colors />
			<normals>
				<normal>[0,0,-1]</normal>
				<normal>[0,0,-1]</normal>
				<normal>[0,0,-1]</normal>
				<normal>[0,0,-1]</normal>
				<normal>[1,0,0]</normal>
				<normal>[0,0,-1]</normal>
				<normal>[1,0,0]</normal>
				<normal>[1,0,0]</normal>
				<normal>[0,0,1]</normal>
				<normal>[1,0,0]</normal>
				<normal>[0,0,1]</normal>
				<normal>[0,0,1]</normal>
				<normal>[-1,0,0]</normal>
				<normal>[0,0,1]</normal>
				<normal>[-1,0,0]</normal>
				<normal>[0,0,-1]</normal>
				<normal>[0,1,0]</normal>
				<normal>[0,0,1]</normal>
				<normal>[1,0,0]</normal>
				<normal>[0,0,-1]</normal>
				<normal>[0,-1,0]</normal>
				<normal>[0,0,-1]</normal>
				<normal>[0,-1,0]</normal>
				<normal>[0,-1,0]</normal>
			</normals>
			<uvsets>
				<uvset name="uvset1">
					<uvcoord>[1,1]</uvcoord>
					<uvcoord>[1,0]</uvcoord>
					<uvcoord>[0,0]</uvcoord>
					<uvcoord>[0,1]</uvcoord>
					<uvcoord>[1,1]</uvcoord>
					<uvcoord>[1,0]</uvcoord>
					<uvcoord>[0,0]</uvcoord>
					<uvcoord>[0,1]</uvcoord>
					<uvcoord>[1,1]</uvcoord>
					<uvcoord>[1,0]</uvcoord>
					<uvcoord>[0,0]</uvcoord>
					<uvcoord>[0,1]</uvcoord>
					<uvcoord>[1,1]</uvcoord>
					<uvcoord>[1,0]</uvcoord>
					<uvcoord>[0,0]</uvcoord>
					<uvcoord>[0,1]</uvcoord>
					<uvcoord>[1,1]</uvcoord>
					<uvcoord>[1,0]</uvcoord>
					<uvcoord>[0,0]</uvcoord>
					<uvcoord>[0,1]</uvcoord>
					<uvcoord>[1,1]</uvcoord>
					<uvcoord>[1,0]</uvcoord>
					<uvcoord>[0,0]</uvcoord>
					<uvcoord>[0,1]</uvcoord>
				</uvset>
			</uvsets>
			<primitives>
				<triangle materialref="m0">
					<vertex position="0" normal="0" texcoords="[[0,0]]" />
					<vertex position="1" normal="1" texcoords="[[0,1]]" />
					<vertex position="3" normal="2" texcoords="[[0,2]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="0" normal="0" texcoords="[[0,0]]" />
					<vertex position="3" normal="2" texcoords="[[0,2]]" />
					<vertex position="2" normal="3" texcoords="[[0,3]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="2" normal="4" texcoords="[[0,4]]" />
					<vertex position="3" normal="5" texcoords="[[0,5]]" />
					<vertex position="5" normal="6" texcoords="[[0,6]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="2" normal="4" texcoords="[[0,4]]" />
					<vertex position="5" normal="6" texcoords="[[0,6]]" />
					<vertex position="4" normal="7" texcoords="[[0,7]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="4" normal="8" texcoords="[[0,8]]" />
					<vertex position="5" normal="9" texcoords="[[0,9]]" />
					<vertex position="7" normal="10" texcoords="[[0,10]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="4" normal="8" texcoords="[[0,8]]" />
					<vertex position="7" normal="10" texcoords="[[0,10]]" />
					<vertex position="6" normal="11" texcoords="[[0,11]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="6" normal="12" texcoords="[[0,12]]" />
					<vertex position="7" normal="13" texcoords="[[0,13]]" />
					<vertex position="1" normal="14" texcoords="[[0,14]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="6" normal="12" texcoords="[[0,12]]" />
					<vertex position="1" normal="14" texcoords="[[0,14]]" />
					<vertex position="0" normal="15" texcoords="[[0,15]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="1" normal="16" texcoords="[[0,16]]" />
					<vertex position="7" normal="17" texcoords="[[0,17]]" />
					<vertex position="5" normal="18" texcoords="[[0,18]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="1" normal="16" texcoords="[[0,16]]" />
					<vertex position="5" normal="18" texcoords="[[0,18]]" />
					<vertex position="3" normal="19" texcoords="[[0,19]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="6" normal="20" texcoords="[[0,20]]" />
					<vertex position="0" normal="21" texcoords="[[0,21]]" />
					<vertex position="2" normal="22" texcoords="[[0,22]]" />
				</triangle>
				<triangle materialref="m0">
					<vertex position="6" normal="20" texcoords="[[0,20]]" />
					<vertex position="2" normal="22" texcoords="[[0,22]]" />
					<vertex position="4" normal="23" texcoords="[[0,23]]" />
				</triangle>
			</primitives>
		</shape>
	</shapes>
	<materials>
		<material name="default_material" type="phong" id="m0">
			<properties>
				<value name="diffuse" type="float4">[0.8,0.8,0.8,1]</value>
				<value name="shininess" type="float">64</value>
				<value name="specular" type="float4">[1,1,1,1]</value>
			</properties>
			<vertexparameters>
				<value name="normal" type="float3" />
			</vertexparameters>
			<textures />
		</material>
	</materials>
	<world>
		<light></light>
		<transform matrix="[[1.99689,-0.104608,0.0385094,0],[0.158809,2.99406,-0.101799,0],[-0.0697671,0.139598,3.99695,0],[0,0,0,1]]" />
		<body />
		<transform matrix="[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]" />
	</world>
</scene>
